### ISSUE TITLE
Feature request: allow the user to select the default search engine

### ISSUE THREAD

**Issue by YogliB** [interstellard/chatgpt-advanced#187]
Just wanted to express my gratitude for the great work so far! I've been enjoying the extension, but I did notice that DuckDuckGo, the default search engine, doesn't consistently provide the most meaningful results.

I have a suggestion: would it be possible to add an option for users to choose their preferred search engine? It would be fantastic to have the ability to switch to platforms like Reddit, where more relevant discussions and user-generated content are often found. 

This way, users can greatly enhance their browsing experience and effortlessly find the information they need. 

Thanks again!

**Comment by SerafDosSantos** [comment]
If I'm not mistaken, to use Google Search you need to use the Google Search API, which is more complex to set up than do a selection from a dropdown menu...

**Comment by wellmorq** [comment]
There are a simple way to do this. The extension supports duckduckgo bangs : https://duckduckgo.com/bangs
So, you can choose almost any search engine you like.
