### ISSUE TITLE
Show nothing

### ISSUE THREAD

**Issue by voon-becoder** [interstellard/chatgpt-advanced#192]
![Screenshot 2023-06-02 110611](https://github.com/interstellard/chatgpt-advanced/assets/65642506/e9dd88ce-38c7-475a-9679-9ab325f7f5d3)

I have install the latest chatgpt-advanced-3.2.7 version. When i typeing all the info and press enter it will show nothing. However i remove this WebchatGPT the chatGPT will be working as normal. When i install back again WebchatGPT it will not function again.

not function means "When i typeing all the info and press enter it will show nothing."

**Comment by daryll-swer** [comment]
Same here. It seems the problem correlates with latest Chrome version 114.0.5735.90

**Comment by 0xFFFF-maker** [comment]
same!!!

**Comment by Github-nmb** [comment]
same issue!

**Comment by Wasslamenace** [comment]
Same issue with chrome and brave browsers

**Comment by Gatasse** [comment]
same for me on chrome and mozilla

**Comment by Sk8aaron** [comment]
Works now.
just updated to chrome version 114.0.5735.91 by clicking on the 3 dots upper right corner of chrome  --> Help --> About Chrome" then it updates when showing the current version.
Also updated the WebChatGPT extension to version 3.3.4. 
All good now!

**Comment by 0xFFFF-maker** [comment]
I am using the Edge browser, but it doesn't seem to be working.

**Comment by Peron4TheWin** [comment]
Yeah, doesn't work on firefox either

**Comment by Wasslamenace** [comment]
This issue is still occurring on brave :(

**Comment by melroy89** [comment]
Time to move to another extension, too bad WebChatGPT has been acquired.
