### ISSUE TITLE
is the extension not open-source anymore?

### ISSUE THREAD

**Issue by YogliB** [interstellard/chatgpt-advanced#196]
I noticed the latest release doesn't match the version in the stores...

**Comment by qunash** [comment]
Hi, this extension was acquired a month ago. See the [twitter](https://twitter.com/hahahahohohe/status/1658884025870581787) and [discrod](https://discord.com/channels/1060110102188797992/1060526685281329182/1108360750935851092) announcment.

**Comment by melroy89** [comment]
Actually. it's not in good hands. And it doesn't work anymore. Very sad ;(

**Comment by YogliB** [comment]
@melroy89 WDYM you use huggingface, for what?
